/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2;

import com.microsoft.rest.v2.RestProxy;
import com.microsoft.rest.v2.ServiceClient;
import com.microsoft.rest.v2.http.HttpPipeline;
import io.reactivex.annotations.NonNull;

/**
 * Initializes a new instance of the GeneratedDataLakeStorageClient type.
 */
public final class GeneratedDataLakeStorageClient extends ServiceClient {
    /**
     * Specifies the version of the REST protocol used for processing the request. This is required when using shared key authorization.
     */
    private String xMsVersion;

    /**
     * Gets Specifies the version of the REST protocol used for processing the request. This is required when using shared key authorization.
     *
     * @return the xMsVersion value.
     */
    public String xMsVersion() {
        return this.xMsVersion;
    }

    /**
     * Sets Specifies the version of the REST protocol used for processing the request. This is required when using shared key authorization.
     *
     * @param xMsVersion the xMsVersion value.
     * @return the service client itself.
     */
    public GeneratedDataLakeStorageClient withXMsVersion(String xMsVersion) {
        this.xMsVersion = xMsVersion;
        return this;
    }

    /**
     * The Azure Storage scheme name.
     */
    private String scheme;

    /**
     * Gets The Azure Storage scheme name.
     *
     * @return the scheme value.
     */
    public String scheme() {
        return this.scheme;
    }

    /**
     * Sets The Azure Storage scheme name.
     *
     * @param scheme the scheme value.
     * @return the service client itself.
     */
    public GeneratedDataLakeStorageClient withScheme(String scheme) {
        this.scheme = scheme;
        return this;
    }

    /**
     * The Azure Storage account name.
     */
    private String accountName;

    /**
     * Gets The Azure Storage account name.
     *
     * @return the accountName value.
     */
    public String accountName() {
        return this.accountName;
    }

    /**
     * Sets The Azure Storage account name.
     *
     * @param accountName the accountName value.
     * @return the service client itself.
     */
    public GeneratedDataLakeStorageClient withAccountName(String accountName) {
        this.accountName = accountName;
        return this;
    }

    /**
     * The DNS suffix for the Azure Data Lake Storage endpoint.
     */
    private String dnsSuffix;

    /**
     * Gets The DNS suffix for the Azure Data Lake Storage endpoint.
     *
     * @return the dnsSuffix value.
     */
    public String dnsSuffix() {
        return this.dnsSuffix;
    }

    /**
     * Sets The DNS suffix for the Azure Data Lake Storage endpoint.
     *
     * @param dnsSuffix the dnsSuffix value.
     * @return the service client itself.
     */
    public GeneratedDataLakeStorageClient withDnsSuffix(String dnsSuffix) {
        this.dnsSuffix = dnsSuffix;
        return this;
    }

    /**
     * The GeneratedFilesystems object to access its operations.
     */
    private GeneratedFilesystems generatedFilesystems;

    /**
     * Gets the GeneratedFilesystems object to access its operations.
     *
     * @return the GeneratedFilesystems object.
     */
    public GeneratedFilesystems generatedFilesystems() {
        return this.generatedFilesystems;
    }

    /**
     * The GeneratedPaths object to access its operations.
     */
    private GeneratedPaths generatedPaths;

    /**
     * Gets the GeneratedPaths object to access its operations.
     *
     * @return the GeneratedPaths object.
     */
    public GeneratedPaths generatedPaths() {
        return this.generatedPaths;
    }

    /**
     * Initializes an instance of GeneratedDataLakeStorageClient client.
     */
    public GeneratedDataLakeStorageClient() {
        this(RestProxy.createDefaultPipeline());
    }

    /**
     * Initializes an instance of GeneratedDataLakeStorageClient client.
     *
     * @param httpPipeline The HTTP pipeline to send requests through.
     */
    public GeneratedDataLakeStorageClient(@NonNull HttpPipeline httpPipeline) {
        super(httpPipeline);
        this.dnsSuffix = "dfs.core.windows.net";
        this.generatedFilesystems = new GeneratedFilesystems(this);
        this.generatedPaths = new GeneratedPaths(this);
    }
}
