/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The DataLakeStorageError model.
 */
public final class DataLakeStorageError {
    /**
     * The service error response object.
     */
    @JsonProperty(value = "error")
    private DataLakeStorageErrorError error;

    /**
     * Get the error value.
     *
     * @return the error value.
     */
    public DataLakeStorageErrorError error() {
        return this.error;
    }

    /**
     * Set the error value.
     *
     * @param error the error value to set.
     * @return the DataLakeStorageError object itself.
     */
    public DataLakeStorageError withError(DataLakeStorageErrorError error) {
        this.error = error;
        return this;
    }
}
