/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The service error response object.
 */
public final class DataLakeStorageErrorError {
    /**
     * The service error code.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * The service error message.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * Get the code value.
     *
     * @return the code value.
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the code value.
     *
     * @param code the code value to set.
     * @return the DataLakeStorageErrorError object itself.
     */
    public DataLakeStorageErrorError withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value.
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set.
     * @return the DataLakeStorageErrorError object itself.
     */
    public DataLakeStorageErrorError withMessage(String message) {
        this.message = message;
        return this;
    }
}
