/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines headers for List operation.
 */
public final class FilesystemListHeaders {
    /**
     * A UTC date/time value generated by the service that indicates the time
     * at which the response was initiated.
     */
    @JsonProperty(value = "Date")
    private String date;

    /**
     * A server-generated UUID recorded in the analytics logs for
     * troubleshooting and correlation.
     */
    @JsonProperty(value = "x-ms-request-id")
    private String xMsRequestId;

    /**
     * The version of the REST protocol used to process the request.
     */
    @JsonProperty(value = "x-ms-version")
    private String xMsVersion;

    /**
     * If the number of filesystems to be listed exceeds the maxResults limit,
     * a continuation token is returned in this response header.  When a
     * continuation token is returned in the response, it must be specified in
     * a subsequent invocation of the list operation to continue listing the
     * filesystems.
     */
    @JsonProperty(value = "x-ms-continuation")
    private String xMsContinuation;

    /**
     * The content type of list filesystem response. The default content type
     * is application/json.
     */
    @JsonProperty(value = "Content-Type")
    private String contentType;

    /**
     * Get the date value.
     *
     * @return the date value.
     */
    public String date() {
        return this.date;
    }

    /**
     * Set the date value.
     *
     * @param date the date value to set.
     * @return the FilesystemListHeaders object itself.
     */
    public FilesystemListHeaders withDate(String date) {
        this.date = date;
        return this;
    }

    /**
     * Get the xMsRequestId value.
     *
     * @return the xMsRequestId value.
     */
    public String xMsRequestId() {
        return this.xMsRequestId;
    }

    /**
     * Set the xMsRequestId value.
     *
     * @param xMsRequestId the xMsRequestId value to set.
     * @return the FilesystemListHeaders object itself.
     */
    public FilesystemListHeaders withXMsRequestId(String xMsRequestId) {
        this.xMsRequestId = xMsRequestId;
        return this;
    }

    /**
     * Get the xMsVersion value.
     *
     * @return the xMsVersion value.
     */
    public String xMsVersion() {
        return this.xMsVersion;
    }

    /**
     * Set the xMsVersion value.
     *
     * @param xMsVersion the xMsVersion value to set.
     * @return the FilesystemListHeaders object itself.
     */
    public FilesystemListHeaders withXMsVersion(String xMsVersion) {
        this.xMsVersion = xMsVersion;
        return this;
    }

    /**
     * Get the xMsContinuation value.
     *
     * @return the xMsContinuation value.
     */
    public String xMsContinuation() {
        return this.xMsContinuation;
    }

    /**
     * Set the xMsContinuation value.
     *
     * @param xMsContinuation the xMsContinuation value to set.
     * @return the FilesystemListHeaders object itself.
     */
    public FilesystemListHeaders withXMsContinuation(String xMsContinuation) {
        this.xMsContinuation = xMsContinuation;
        return this;
    }

    /**
     * Get the contentType value.
     *
     * @return the contentType value.
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * Set the contentType value.
     *
     * @param contentType the contentType value to set.
     * @return the FilesystemListHeaders object itself.
     */
    public FilesystemListHeaders withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
}
