/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines headers for Create operation.
 */
public final class FilesystemCreateHeaders {
    /**
     * A UTC date/time value generated by the service that indicates the time
     * at which the response was initiated.
     */
    @JsonProperty(value = "Date")
    private String date;

    /**
     * An HTTP entity tag associated with the filesystem.
     */
    @JsonProperty(value = "ETag")
    private String eTag;

    /**
     * The data and time the filesystem was last modified.  Operations on files
     * and directories do not affect the last modified time.
     */
    @JsonProperty(value = "Last-Modified")
    private String lastModified;

    /**
     * A server-generated UUID recorded in the analytics logs for
     * troubleshooting and correlation.
     */
    @JsonProperty(value = "x-ms-request-id")
    private String xMsRequestId;

    /**
     * The version of the REST protocol used to process the request.
     */
    @JsonProperty(value = "x-ms-version")
    private String xMsVersion;

    /**
     * A bool string indicates whether the namespace feature is enabled. If
     * "true", the namespace is enabled for the filesystem.
     */
    @JsonProperty(value = "x-ms-namespace-enabled")
    private String xMsNamespaceEnabled;

    /**
     * Get the date value.
     *
     * @return the date value.
     */
    public String date() {
        return this.date;
    }

    /**
     * Set the date value.
     *
     * @param date the date value to set.
     * @return the FilesystemCreateHeaders object itself.
     */
    public FilesystemCreateHeaders withDate(String date) {
        this.date = date;
        return this;
    }

    /**
     * Get the eTag value.
     *
     * @return the eTag value.
     */
    public String eTag() {
        return this.eTag;
    }

    /**
     * Set the eTag value.
     *
     * @param eTag the eTag value to set.
     * @return the FilesystemCreateHeaders object itself.
     */
    public FilesystemCreateHeaders withETag(String eTag) {
        this.eTag = eTag;
        return this;
    }

    /**
     * Get the lastModified value.
     *
     * @return the lastModified value.
     */
    public String lastModified() {
        return this.lastModified;
    }

    /**
     * Set the lastModified value.
     *
     * @param lastModified the lastModified value to set.
     * @return the FilesystemCreateHeaders object itself.
     */
    public FilesystemCreateHeaders withLastModified(String lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    /**
     * Get the xMsRequestId value.
     *
     * @return the xMsRequestId value.
     */
    public String xMsRequestId() {
        return this.xMsRequestId;
    }

    /**
     * Set the xMsRequestId value.
     *
     * @param xMsRequestId the xMsRequestId value to set.
     * @return the FilesystemCreateHeaders object itself.
     */
    public FilesystemCreateHeaders withXMsRequestId(String xMsRequestId) {
        this.xMsRequestId = xMsRequestId;
        return this;
    }

    /**
     * Get the xMsVersion value.
     *
     * @return the xMsVersion value.
     */
    public String xMsVersion() {
        return this.xMsVersion;
    }

    /**
     * Set the xMsVersion value.
     *
     * @param xMsVersion the xMsVersion value to set.
     * @return the FilesystemCreateHeaders object itself.
     */
    public FilesystemCreateHeaders withXMsVersion(String xMsVersion) {
        this.xMsVersion = xMsVersion;
        return this;
    }

    /**
     * Get the xMsNamespaceEnabled value.
     *
     * @return the xMsNamespaceEnabled value.
     */
    public String xMsNamespaceEnabled() {
        return this.xMsNamespaceEnabled;
    }

    /**
     * Set the xMsNamespaceEnabled value.
     *
     * @param xMsNamespaceEnabled the xMsNamespaceEnabled value to set.
     * @return the FilesystemCreateHeaders object itself.
     */
    public FilesystemCreateHeaders withXMsNamespaceEnabled(String xMsNamespaceEnabled) {
        this.xMsNamespaceEnabled = xMsNamespaceEnabled;
        return this;
    }
}
