/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines headers for GetProperties operation.
 */
public final class FilesystemGetPropertiesHeaders {
    /**
     * A UTC date/time value generated by the service that indicates the time
     * at which the response was initiated.
     */
    @JsonProperty(value = "Date")
    private String date;

    /**
     * An HTTP entity tag associated with the filesystem.  Changes to
     * filesystem properties affect the entity tag, but operations on files and
     * directories do not.
     */
    @JsonProperty(value = "ETag")
    private String eTag;

    /**
     * The data and time the filesystem was last modified.  Changes to
     * filesystem properties update the last modified time, but operations on
     * files and directories do not.
     */
    @JsonProperty(value = "Last-Modified")
    private String lastModified;

    /**
     * A server-generated UUID recorded in the analytics logs for
     * troubleshooting and correlation.
     */
    @JsonProperty(value = "x-ms-request-id")
    private String xMsRequestId;

    /**
     * The version of the REST protocol used to process the request.
     */
    @JsonProperty(value = "x-ms-version")
    private String xMsVersion;

    /**
     * The user-defined properties associated with the filesystem.  A
     * comma-separated list of name and value pairs in the format "n1=v1,
     * n2=v2, ...", where each value is a base64 encoded string. Note that the
     * string may only contain ASCII characters in the ISO-8859-1 character
     * set.
     */
    @JsonProperty(value = "x-ms-properties")
    private String xMsProperties;

    /**
     * A bool string indicates whether the namespace feature is enabled. If
     * "true", the namespace is enabled for the filesystem.
     */
    @JsonProperty(value = "x-ms-namespace-enabled")
    private String xMsNamespaceEnabled;

    /**
     * Get the date value.
     *
     * @return the date value.
     */
    public String date() {
        return this.date;
    }

    /**
     * Set the date value.
     *
     * @param date the date value to set.
     * @return the FilesystemGetPropertiesHeaders object itself.
     */
    public FilesystemGetPropertiesHeaders withDate(String date) {
        this.date = date;
        return this;
    }

    /**
     * Get the eTag value.
     *
     * @return the eTag value.
     */
    public String eTag() {
        return this.eTag;
    }

    /**
     * Set the eTag value.
     *
     * @param eTag the eTag value to set.
     * @return the FilesystemGetPropertiesHeaders object itself.
     */
    public FilesystemGetPropertiesHeaders withETag(String eTag) {
        this.eTag = eTag;
        return this;
    }

    /**
     * Get the lastModified value.
     *
     * @return the lastModified value.
     */
    public String lastModified() {
        return this.lastModified;
    }

    /**
     * Set the lastModified value.
     *
     * @param lastModified the lastModified value to set.
     * @return the FilesystemGetPropertiesHeaders object itself.
     */
    public FilesystemGetPropertiesHeaders withLastModified(String lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    /**
     * Get the xMsRequestId value.
     *
     * @return the xMsRequestId value.
     */
    public String xMsRequestId() {
        return this.xMsRequestId;
    }

    /**
     * Set the xMsRequestId value.
     *
     * @param xMsRequestId the xMsRequestId value to set.
     * @return the FilesystemGetPropertiesHeaders object itself.
     */
    public FilesystemGetPropertiesHeaders withXMsRequestId(String xMsRequestId) {
        this.xMsRequestId = xMsRequestId;
        return this;
    }

    /**
     * Get the xMsVersion value.
     *
     * @return the xMsVersion value.
     */
    public String xMsVersion() {
        return this.xMsVersion;
    }

    /**
     * Set the xMsVersion value.
     *
     * @param xMsVersion the xMsVersion value to set.
     * @return the FilesystemGetPropertiesHeaders object itself.
     */
    public FilesystemGetPropertiesHeaders withXMsVersion(String xMsVersion) {
        this.xMsVersion = xMsVersion;
        return this;
    }

    /**
     * Get the xMsProperties value.
     *
     * @return the xMsProperties value.
     */
    public String xMsProperties() {
        return this.xMsProperties;
    }

    /**
     * Set the xMsProperties value.
     *
     * @param xMsProperties the xMsProperties value to set.
     * @return the FilesystemGetPropertiesHeaders object itself.
     */
    public FilesystemGetPropertiesHeaders withXMsProperties(String xMsProperties) {
        this.xMsProperties = xMsProperties;
        return this;
    }

    /**
     * Get the xMsNamespaceEnabled value.
     *
     * @return the xMsNamespaceEnabled value.
     */
    public String xMsNamespaceEnabled() {
        return this.xMsNamespaceEnabled;
    }

    /**
     * Set the xMsNamespaceEnabled value.
     *
     * @param xMsNamespaceEnabled the xMsNamespaceEnabled value to set.
     * @return the FilesystemGetPropertiesHeaders object itself.
     */
    public FilesystemGetPropertiesHeaders withXMsNamespaceEnabled(String xMsNamespaceEnabled) {
        this.xMsNamespaceEnabled = xMsNamespaceEnabled;
        return this;
    }
}
