/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Filesystem model.
 */
public final class Filesystem {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The lastModified property.
     */
    @JsonProperty(value = "lastModified")
    private String lastModified;

    /**
     * The eTag property.
     */
    @JsonProperty(value = "eTag")
    private String eTag;

    /**
     * Get the name value.
     *
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set.
     * @return the Filesystem object itself.
     */
    public Filesystem withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the lastModified value.
     *
     * @return the lastModified value.
     */
    public String lastModified() {
        return this.lastModified;
    }

    /**
     * Set the lastModified value.
     *
     * @param lastModified the lastModified value to set.
     * @return the Filesystem object itself.
     */
    public Filesystem withLastModified(String lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    /**
     * Get the eTag value.
     *
     * @return the eTag value.
     */
    public String eTag() {
        return this.eTag;
    }

    /**
     * Set the eTag value.
     *
     * @param eTag the eTag value to set.
     * @return the Filesystem object itself.
     */
    public Filesystem withETag(String eTag) {
        this.eTag = eTag;
        return this;
    }
}
