/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The FilesystemList model.
 */
public final class FilesystemList {
    /**
     * The filesystems property.
     */
    @JsonProperty(value = "filesystems")
    private List<Filesystem> filesystems;

    /**
     * Get the filesystems value.
     *
     * @return the filesystems value.
     */
    public List<Filesystem> filesystems() {
        return this.filesystems;
    }

    /**
     * Set the filesystems value.
     *
     * @param filesystems the filesystems value to set.
     * @return the FilesystemList object itself.
     */
    public FilesystemList withFilesystems(List<Filesystem> filesystems) {
        this.filesystems = filesystems;
        return this;
    }
}
