/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines headers for GetProperties operation.
 */
public final class PathGetPropertiesHeaders {
    /**
     * Indicates that the service supports requests for partial file content.
     */
    @JsonProperty(value = "Accept-Ranges")
    private String acceptRanges;

    /**
     * If the Cache-Control request header has previously been set for the
     * resource, that value is returned in this header.
     */
    @JsonProperty(value = "Cache-Control")
    private String cacheControl;

    /**
     * If the Content-Disposition request header has previously been set for
     * the resource, that value is returned in this header.
     */
    @JsonProperty(value = "Content-Disposition")
    private String contentDisposition;

    /**
     * If the Content-Encoding request header has previously been set for the
     * resource, that value is returned in this header.
     */
    @JsonProperty(value = "Content-Encoding")
    private String contentEncoding;

    /**
     * If the Content-Language request header has previously been set for the
     * resource, that value is returned in this header.
     */
    @JsonProperty(value = "Content-Language")
    private String contentLanguage;

    /**
     * The size of the resource in bytes.
     */
    @JsonProperty(value = "Content-Length")
    private Long contentLength;

    /**
     * Indicates the range of bytes returned in the event that the client
     * requested a subset of the file by setting the Range request header.
     */
    @JsonProperty(value = "Content-Range")
    private String contentRange;

    /**
     * The content type specified for the resource. If no content type was
     * specified, the default content type is application/octet-stream.
     */
    @JsonProperty(value = "Content-Type")
    private String contentType;

    /**
     * A UTC date/time value generated by the service that indicates the time
     * at which the response was initiated.
     */
    @JsonProperty(value = "Date")
    private String date;

    /**
     * An HTTP entity tag associated with the file or directory.
     */
    @JsonProperty(value = "ETag")
    private String eTag;

    /**
     * The data and time the file or directory was last modified.  Write
     * operations on the file or directory update the last modified time.
     */
    @JsonProperty(value = "Last-Modified")
    private String lastModified;

    /**
     * A server-generated UUID recorded in the analytics logs for
     * troubleshooting and correlation.
     */
    @JsonProperty(value = "x-ms-request-id")
    private String xMsRequestId;

    /**
     * The version of the REST protocol used to process the request.
     */
    @JsonProperty(value = "x-ms-version")
    private String xMsVersion;

    /**
     * The type of the resource.  The value may be "file" or "directory".  If
     * not set, the value is "file".
     */
    @JsonProperty(value = "x-ms-resource-type")
    private String xMsResourceType;

    /**
     * The user-defined properties associated with the file or directory, in
     * the format of a comma-separated list of name and value pairs "n1=v1,
     * n2=v2, ...", where each value is a base64 encoded string. Note that the
     * string may only contain ASCII characters in the ISO-8859-1 character
     * set.
     */
    @JsonProperty(value = "x-ms-properties")
    private String xMsProperties;

    /**
     * The owner of the file or directory. Included in the response if
     * Hierarchical Namespace is enabled for the account.
     */
    @JsonProperty(value = "x-ms-owner")
    private String xMsOwner;

    /**
     * The owning group of the file or directory. Included in the response if
     * Hierarchical Namespace is enabled for the account.
     */
    @JsonProperty(value = "x-ms-group")
    private String xMsGroup;

    /**
     * The POSIX access permissions for the file owner, the file owning group,
     * and others. Included in the response if Hierarchical Namespace is
     * enabled for the account.
     */
    @JsonProperty(value = "x-ms-permissions")
    private String xMsPermissions;

    /**
     * The POSIX access control list for the file or directory.  Included in
     * the response only if the action is "getAccessControl" and Hierarchical
     * Namespace is enabled for the account.
     */
    @JsonProperty(value = "x-ms-acl")
    private String xMsAcl;

    /**
     * When a resource is leased, specifies whether the lease is of infinite or
     * fixed duration.
     */
    @JsonProperty(value = "x-ms-lease-duration")
    private String xMsLeaseDuration;

    /**
     * Lease state of the resource.
     */
    @JsonProperty(value = "x-ms-lease-state")
    private String xMsLeaseState;

    /**
     * The lease status of the resource.
     */
    @JsonProperty(value = "x-ms-lease-status")
    private String xMsLeaseStatus;

    /**
     * Get the acceptRanges value.
     *
     * @return the acceptRanges value.
     */
    public String acceptRanges() {
        return this.acceptRanges;
    }

    /**
     * Set the acceptRanges value.
     *
     * @param acceptRanges the acceptRanges value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withAcceptRanges(String acceptRanges) {
        this.acceptRanges = acceptRanges;
        return this;
    }

    /**
     * Get the cacheControl value.
     *
     * @return the cacheControl value.
     */
    public String cacheControl() {
        return this.cacheControl;
    }

    /**
     * Set the cacheControl value.
     *
     * @param cacheControl the cacheControl value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withCacheControl(String cacheControl) {
        this.cacheControl = cacheControl;
        return this;
    }

    /**
     * Get the contentDisposition value.
     *
     * @return the contentDisposition value.
     */
    public String contentDisposition() {
        return this.contentDisposition;
    }

    /**
     * Set the contentDisposition value.
     *
     * @param contentDisposition the contentDisposition value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withContentDisposition(String contentDisposition) {
        this.contentDisposition = contentDisposition;
        return this;
    }

    /**
     * Get the contentEncoding value.
     *
     * @return the contentEncoding value.
     */
    public String contentEncoding() {
        return this.contentEncoding;
    }

    /**
     * Set the contentEncoding value.
     *
     * @param contentEncoding the contentEncoding value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withContentEncoding(String contentEncoding) {
        this.contentEncoding = contentEncoding;
        return this;
    }

    /**
     * Get the contentLanguage value.
     *
     * @return the contentLanguage value.
     */
    public String contentLanguage() {
        return this.contentLanguage;
    }

    /**
     * Set the contentLanguage value.
     *
     * @param contentLanguage the contentLanguage value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withContentLanguage(String contentLanguage) {
        this.contentLanguage = contentLanguage;
        return this;
    }

    /**
     * Get the contentLength value.
     *
     * @return the contentLength value.
     */
    public Long contentLength() {
        return this.contentLength;
    }

    /**
     * Set the contentLength value.
     *
     * @param contentLength the contentLength value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withContentLength(Long contentLength) {
        this.contentLength = contentLength;
        return this;
    }

    /**
     * Get the contentRange value.
     *
     * @return the contentRange value.
     */
    public String contentRange() {
        return this.contentRange;
    }

    /**
     * Set the contentRange value.
     *
     * @param contentRange the contentRange value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withContentRange(String contentRange) {
        this.contentRange = contentRange;
        return this;
    }

    /**
     * Get the contentType value.
     *
     * @return the contentType value.
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * Set the contentType value.
     *
     * @param contentType the contentType value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }

    /**
     * Get the date value.
     *
     * @return the date value.
     */
    public String date() {
        return this.date;
    }

    /**
     * Set the date value.
     *
     * @param date the date value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withDate(String date) {
        this.date = date;
        return this;
    }

    /**
     * Get the eTag value.
     *
     * @return the eTag value.
     */
    public String eTag() {
        return this.eTag;
    }

    /**
     * Set the eTag value.
     *
     * @param eTag the eTag value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withETag(String eTag) {
        this.eTag = eTag;
        return this;
    }

    /**
     * Get the lastModified value.
     *
     * @return the lastModified value.
     */
    public String lastModified() {
        return this.lastModified;
    }

    /**
     * Set the lastModified value.
     *
     * @param lastModified the lastModified value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withLastModified(String lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    /**
     * Get the xMsRequestId value.
     *
     * @return the xMsRequestId value.
     */
    public String xMsRequestId() {
        return this.xMsRequestId;
    }

    /**
     * Set the xMsRequestId value.
     *
     * @param xMsRequestId the xMsRequestId value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsRequestId(String xMsRequestId) {
        this.xMsRequestId = xMsRequestId;
        return this;
    }

    /**
     * Get the xMsVersion value.
     *
     * @return the xMsVersion value.
     */
    public String xMsVersion() {
        return this.xMsVersion;
    }

    /**
     * Set the xMsVersion value.
     *
     * @param xMsVersion the xMsVersion value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsVersion(String xMsVersion) {
        this.xMsVersion = xMsVersion;
        return this;
    }

    /**
     * Get the xMsResourceType value.
     *
     * @return the xMsResourceType value.
     */
    public String xMsResourceType() {
        return this.xMsResourceType;
    }

    /**
     * Set the xMsResourceType value.
     *
     * @param xMsResourceType the xMsResourceType value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsResourceType(String xMsResourceType) {
        this.xMsResourceType = xMsResourceType;
        return this;
    }

    /**
     * Get the xMsProperties value.
     *
     * @return the xMsProperties value.
     */
    public String xMsProperties() {
        return this.xMsProperties;
    }

    /**
     * Set the xMsProperties value.
     *
     * @param xMsProperties the xMsProperties value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsProperties(String xMsProperties) {
        this.xMsProperties = xMsProperties;
        return this;
    }

    /**
     * Get the xMsOwner value.
     *
     * @return the xMsOwner value.
     */
    public String xMsOwner() {
        return this.xMsOwner;
    }

    /**
     * Set the xMsOwner value.
     *
     * @param xMsOwner the xMsOwner value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsOwner(String xMsOwner) {
        this.xMsOwner = xMsOwner;
        return this;
    }

    /**
     * Get the xMsGroup value.
     *
     * @return the xMsGroup value.
     */
    public String xMsGroup() {
        return this.xMsGroup;
    }

    /**
     * Set the xMsGroup value.
     *
     * @param xMsGroup the xMsGroup value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsGroup(String xMsGroup) {
        this.xMsGroup = xMsGroup;
        return this;
    }

    /**
     * Get the xMsPermissions value.
     *
     * @return the xMsPermissions value.
     */
    public String xMsPermissions() {
        return this.xMsPermissions;
    }

    /**
     * Set the xMsPermissions value.
     *
     * @param xMsPermissions the xMsPermissions value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsPermissions(String xMsPermissions) {
        this.xMsPermissions = xMsPermissions;
        return this;
    }

    /**
     * Get the xMsAcl value.
     *
     * @return the xMsAcl value.
     */
    public String xMsAcl() {
        return this.xMsAcl;
    }

    /**
     * Set the xMsAcl value.
     *
     * @param xMsAcl the xMsAcl value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsAcl(String xMsAcl) {
        this.xMsAcl = xMsAcl;
        return this;
    }

    /**
     * Get the xMsLeaseDuration value.
     *
     * @return the xMsLeaseDuration value.
     */
    public String xMsLeaseDuration() {
        return this.xMsLeaseDuration;
    }

    /**
     * Set the xMsLeaseDuration value.
     *
     * @param xMsLeaseDuration the xMsLeaseDuration value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsLeaseDuration(String xMsLeaseDuration) {
        this.xMsLeaseDuration = xMsLeaseDuration;
        return this;
    }

    /**
     * Get the xMsLeaseState value.
     *
     * @return the xMsLeaseState value.
     */
    public String xMsLeaseState() {
        return this.xMsLeaseState;
    }

    /**
     * Set the xMsLeaseState value.
     *
     * @param xMsLeaseState the xMsLeaseState value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsLeaseState(String xMsLeaseState) {
        this.xMsLeaseState = xMsLeaseState;
        return this;
    }

    /**
     * Get the xMsLeaseStatus value.
     *
     * @return the xMsLeaseStatus value.
     */
    public String xMsLeaseStatus() {
        return this.xMsLeaseStatus;
    }

    /**
     * Set the xMsLeaseStatus value.
     *
     * @param xMsLeaseStatus the xMsLeaseStatus value to set.
     * @return the PathGetPropertiesHeaders object itself.
     */
    public PathGetPropertiesHeaders withXMsLeaseStatus(String xMsLeaseStatus) {
        this.xMsLeaseStatus = xMsLeaseStatus;
        return this;
    }
}
