/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines headers for Create operation.
 */
public final class PathCreateHeaders {
    /**
     * A UTC date/time value generated by the service that indicates the time
     * at which the response was initiated.
     */
    @JsonProperty(value = "Date")
    private String date;

    /**
     * An HTTP entity tag associated with the file or directory.
     */
    @JsonProperty(value = "ETag")
    private String eTag;

    /**
     * The data and time the file or directory was last modified.  Write
     * operations on the file or directory update the last modified time.
     */
    @JsonProperty(value = "Last-Modified")
    private String lastModified;

    /**
     * A server-generated UUID recorded in the analytics logs for
     * troubleshooting and correlation.
     */
    @JsonProperty(value = "x-ms-request-id")
    private String xMsRequestId;

    /**
     * The version of the REST protocol used to process the request.
     */
    @JsonProperty(value = "x-ms-version")
    private String xMsVersion;

    /**
     * When renaming a directory, the number of paths that are renamed with
     * each invocation is limited.  If the number of paths to be renamed
     * exceeds this limit, a continuation token is returned in this response
     * header.  When a continuation token is returned in the response, it must
     * be specified in a subsequent invocation of the rename operation to
     * continue renaming the directory.
     */
    @JsonProperty(value = "x-ms-continuation")
    private String xMsContinuation;

    /**
     * The size of the resource in bytes.
     */
    @JsonProperty(value = "Content-Length")
    private Long contentLength;

    /**
     * Get the date value.
     *
     * @return the date value.
     */
    public String date() {
        return this.date;
    }

    /**
     * Set the date value.
     *
     * @param date the date value to set.
     * @return the PathCreateHeaders object itself.
     */
    public PathCreateHeaders withDate(String date) {
        this.date = date;
        return this;
    }

    /**
     * Get the eTag value.
     *
     * @return the eTag value.
     */
    public String eTag() {
        return this.eTag;
    }

    /**
     * Set the eTag value.
     *
     * @param eTag the eTag value to set.
     * @return the PathCreateHeaders object itself.
     */
    public PathCreateHeaders withETag(String eTag) {
        this.eTag = eTag;
        return this;
    }

    /**
     * Get the lastModified value.
     *
     * @return the lastModified value.
     */
    public String lastModified() {
        return this.lastModified;
    }

    /**
     * Set the lastModified value.
     *
     * @param lastModified the lastModified value to set.
     * @return the PathCreateHeaders object itself.
     */
    public PathCreateHeaders withLastModified(String lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    /**
     * Get the xMsRequestId value.
     *
     * @return the xMsRequestId value.
     */
    public String xMsRequestId() {
        return this.xMsRequestId;
    }

    /**
     * Set the xMsRequestId value.
     *
     * @param xMsRequestId the xMsRequestId value to set.
     * @return the PathCreateHeaders object itself.
     */
    public PathCreateHeaders withXMsRequestId(String xMsRequestId) {
        this.xMsRequestId = xMsRequestId;
        return this;
    }

    /**
     * Get the xMsVersion value.
     *
     * @return the xMsVersion value.
     */
    public String xMsVersion() {
        return this.xMsVersion;
    }

    /**
     * Set the xMsVersion value.
     *
     * @param xMsVersion the xMsVersion value to set.
     * @return the PathCreateHeaders object itself.
     */
    public PathCreateHeaders withXMsVersion(String xMsVersion) {
        this.xMsVersion = xMsVersion;
        return this;
    }

    /**
     * Get the xMsContinuation value.
     *
     * @return the xMsContinuation value.
     */
    public String xMsContinuation() {
        return this.xMsContinuation;
    }

    /**
     * Set the xMsContinuation value.
     *
     * @param xMsContinuation the xMsContinuation value to set.
     * @return the PathCreateHeaders object itself.
     */
    public PathCreateHeaders withXMsContinuation(String xMsContinuation) {
        this.xMsContinuation = xMsContinuation;
        return this;
    }

    /**
     * Get the contentLength value.
     *
     * @return the contentLength value.
     */
    public Long contentLength() {
        return this.contentLength;
    }

    /**
     * Set the contentLength value.
     *
     * @param contentLength the contentLength value to set.
     * @return the PathCreateHeaders object itself.
     */
    public PathCreateHeaders withContentLength(Long contentLength) {
        this.contentLength = contentLength;
        return this;
    }
}
