/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines headers for Lease operation.
 */
public final class PathLeaseHeaders {
    /**
     * A UTC date/time value generated by the service that indicates the time
     * at which the response was initiated.
     */
    @JsonProperty(value = "Date")
    private String date;

    /**
     * An HTTP entity tag associated with the file or directory.
     */
    @JsonProperty(value = "ETag")
    private String eTag;

    /**
     * The data and time the file or directory was last modified.  Write
     * operations on the file or directory update the last modified time.
     */
    @JsonProperty(value = "Last-Modified")
    private String lastModified;

    /**
     * A server-generated UUID recorded in the analytics logs for
     * troubleshooting and correlation.
     */
    @JsonProperty(value = "x-ms-request-id")
    private String xMsRequestId;

    /**
     * The version of the REST protocol used to process the request.
     */
    @JsonProperty(value = "x-ms-version")
    private String xMsVersion;

    /**
     * A successful "acquire" action returns the lease ID.
     */
    @JsonProperty(value = "x-ms-lease-id")
    private String xMsLeaseId;

    /**
     * The time remaining in the lease period in seconds.
     */
    @JsonProperty(value = "x-ms-lease-time")
    private String xMsLeaseTime;

    /**
     * Get the date value.
     *
     * @return the date value.
     */
    public String date() {
        return this.date;
    }

    /**
     * Set the date value.
     *
     * @param date the date value to set.
     * @return the PathLeaseHeaders object itself.
     */
    public PathLeaseHeaders withDate(String date) {
        this.date = date;
        return this;
    }

    /**
     * Get the eTag value.
     *
     * @return the eTag value.
     */
    public String eTag() {
        return this.eTag;
    }

    /**
     * Set the eTag value.
     *
     * @param eTag the eTag value to set.
     * @return the PathLeaseHeaders object itself.
     */
    public PathLeaseHeaders withETag(String eTag) {
        this.eTag = eTag;
        return this;
    }

    /**
     * Get the lastModified value.
     *
     * @return the lastModified value.
     */
    public String lastModified() {
        return this.lastModified;
    }

    /**
     * Set the lastModified value.
     *
     * @param lastModified the lastModified value to set.
     * @return the PathLeaseHeaders object itself.
     */
    public PathLeaseHeaders withLastModified(String lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    /**
     * Get the xMsRequestId value.
     *
     * @return the xMsRequestId value.
     */
    public String xMsRequestId() {
        return this.xMsRequestId;
    }

    /**
     * Set the xMsRequestId value.
     *
     * @param xMsRequestId the xMsRequestId value to set.
     * @return the PathLeaseHeaders object itself.
     */
    public PathLeaseHeaders withXMsRequestId(String xMsRequestId) {
        this.xMsRequestId = xMsRequestId;
        return this;
    }

    /**
     * Get the xMsVersion value.
     *
     * @return the xMsVersion value.
     */
    public String xMsVersion() {
        return this.xMsVersion;
    }

    /**
     * Set the xMsVersion value.
     *
     * @param xMsVersion the xMsVersion value to set.
     * @return the PathLeaseHeaders object itself.
     */
    public PathLeaseHeaders withXMsVersion(String xMsVersion) {
        this.xMsVersion = xMsVersion;
        return this;
    }

    /**
     * Get the xMsLeaseId value.
     *
     * @return the xMsLeaseId value.
     */
    public String xMsLeaseId() {
        return this.xMsLeaseId;
    }

    /**
     * Set the xMsLeaseId value.
     *
     * @param xMsLeaseId the xMsLeaseId value to set.
     * @return the PathLeaseHeaders object itself.
     */
    public PathLeaseHeaders withXMsLeaseId(String xMsLeaseId) {
        this.xMsLeaseId = xMsLeaseId;
        return this;
    }

    /**
     * Get the xMsLeaseTime value.
     *
     * @return the xMsLeaseTime value.
     */
    public String xMsLeaseTime() {
        return this.xMsLeaseTime;
    }

    /**
     * Set the xMsLeaseTime value.
     *
     * @param xMsLeaseTime the xMsLeaseTime value to set.
     * @return the PathLeaseHeaders object itself.
     */
    public PathLeaseHeaders withXMsLeaseTime(String xMsLeaseTime) {
        this.xMsLeaseTime = xMsLeaseTime;
        return this;
    }
}
