/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.storage.adlsg2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Path model.
 */
public final class Path {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The isDirectory property.
     */
    @JsonProperty(value = "isDirectory")
    private Boolean isDirectory;

    /**
     * The lastModified property.
     */
    @JsonProperty(value = "lastModified")
    private String lastModified;

    /**
     * The eTag property.
     */
    @JsonProperty(value = "eTag")
    private String eTag;

    /**
     * The contentLength property.
     */
    @JsonProperty(value = "contentLength")
    private Long contentLength;

    /**
     * The owner property.
     */
    @JsonProperty(value = "owner")
    private String owner;

    /**
     * The group property.
     */
    @JsonProperty(value = "group")
    private String group;

    /**
     * The permissions property.
     */
    @JsonProperty(value = "permissions")
    private String permissions;

    /**
     * Get the name value.
     *
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set.
     * @return the Path object itself.
     */
    public Path withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the isDirectory value.
     *
     * @return the isDirectory value.
     */
    public Boolean isDirectory() {
        return this.isDirectory;
    }

    /**
     * Set the isDirectory value.
     *
     * @param isDirectory the isDirectory value to set.
     * @return the Path object itself.
     */
    public Path withIsDirectory(Boolean isDirectory) {
        this.isDirectory = isDirectory;
        return this;
    }

    /**
     * Get the lastModified value.
     *
     * @return the lastModified value.
     */
    public String lastModified() {
        return this.lastModified;
    }

    /**
     * Set the lastModified value.
     *
     * @param lastModified the lastModified value to set.
     * @return the Path object itself.
     */
    public Path withLastModified(String lastModified) {
        this.lastModified = lastModified;
        return this;
    }

    /**
     * Get the eTag value.
     *
     * @return the eTag value.
     */
    public String eTag() {
        return this.eTag;
    }

    /**
     * Set the eTag value.
     *
     * @param eTag the eTag value to set.
     * @return the Path object itself.
     */
    public Path withETag(String eTag) {
        this.eTag = eTag;
        return this;
    }

    /**
     * Get the contentLength value.
     *
     * @return the contentLength value.
     */
    public Long contentLength() {
        return this.contentLength;
    }

    /**
     * Set the contentLength value.
     *
     * @param contentLength the contentLength value to set.
     * @return the Path object itself.
     */
    public Path withContentLength(Long contentLength) {
        this.contentLength = contentLength;
        return this;
    }

    /**
     * Get the owner value.
     *
     * @return the owner value.
     */
    public String owner() {
        return this.owner;
    }

    /**
     * Set the owner value.
     *
     * @param owner the owner value to set.
     * @return the Path object itself.
     */
    public Path withOwner(String owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get the group value.
     *
     * @return the group value.
     */
    public String group() {
        return this.group;
    }

    /**
     * Set the group value.
     *
     * @param group the group value to set.
     * @return the Path object itself.
     */
    public Path withGroup(String group) {
        this.group = group;
        return this;
    }

    /**
     * Get the permissions value.
     *
     * @return the permissions value.
     */
    public String permissions() {
        return this.permissions;
    }

    /**
     * Set the permissions value.
     *
     * @param permissions the permissions value to set.
     * @return the Path object itself.
     */
    public Path withPermissions(String permissions) {
        this.permissions = permissions;
        return this;
    }
}
